/* eslint-disable */
window.APARTMENTS_DATA = [
  { id: 1, city: 'moscow', cityName: 'Москва', type: 'daily', title: 'Студия в центре, вид на парк', meta: 'Арбат · до 2 гостей', price: 'от 3 500 ₽', priceUnit: '/ ночь', priceNight: 3500, priceMonth: 0, image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=400&fit=crop', description: 'Уютная студия с панорамным видом на парк. Полностью оборудованная кухня, современная мебель, кондиционер и быстрый Wi‑Fi.', amenities: ['Wi‑Fi', 'Кондиционер', 'Кухня', 'Стиральная машина', 'Телевизор', 'Утюг'] },
  { id: 2, city: 'moscow', cityName: 'Москва', type: 'long', title: 'Двухкомнатная у метро', meta: 'Тверская · до 4 гостей', price: 'от 85 000 ₽', priceUnit: '/ месяц', priceNight: 0, priceMonth: 85000, image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&h=400&fit=crop', description: 'Просторная двухкомнатная квартира в 5 минутах от метро. Отдельная кухня, две спальни, гостиная.', amenities: ['Wi‑Fi', 'Кондиционер', 'Кухня', 'Стиральная машина', 'Телевизор', 'Посудомоечная машина', 'Балкон'] },
  { id: 3, city: 'moscow', cityName: 'Москва', type: 'daily', title: 'Апартаменты с кухней-гостиной', meta: 'Патриаршие · до 3 гостей', price: 'от 5 200 ₽', priceUnit: '/ ночь', priceNight: 5200, priceMonth: 0, image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&h=400&fit=crop', description: 'Современные апартаменты в самом центре. Открытая кухня-гостиная, отдельная спальня.', amenities: ['Wi‑Fi', 'Кондиционер', 'Кухня', 'Стиральная машина', 'Телевизор', 'Кофемашина'] },
  { id: 4, city: 'moscow', cityName: 'Москва', type: 'long', title: 'Однокомнатная с балконом', meta: 'Хамовники · до 2 гостей', price: 'от 65 000 ₽', priceUnit: '/ месяц', priceNight: 0, priceMonth: 65000, image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600&h=400&fit=crop', description: 'Тихая однокомнатная квартира с балконом в жилом районе. Удобная планировка, новая мебель.', amenities: ['Wi‑Fi', 'Кондиционер', 'Кухня', 'Стиральная машина', 'Балкон', 'Утюг'] },
  { id: 5, city: 'moscow', cityName: 'Москва', type: 'daily', title: 'Лофт в историческом центре', meta: 'Замоскворечье · до 4 гостей', price: 'от 7 800 ₽', priceUnit: '/ ночь', priceNight: 7800, priceMonth: 0, image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=600&h=400&fit=crop', description: 'Уникальный лофт в отреставрированном здании. Высокие потолки, панорамные окна.', amenities: ['Wi‑Fi', 'Кондиционер', 'Кухня', 'Стиральная машина', 'Телевизор', 'Парковка'] },
  { id: 6, city: 'moscow', cityName: 'Москва', type: 'long', title: 'Трёхкомнатная для семьи', meta: 'Сокольники · до 6 гостей', price: 'от 120 000 ₽', priceUnit: '/ месяц', priceNight: 0, priceMonth: 120000, image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=600&h=400&fit=crop', description: 'Большая трёхкомнатная квартира рядом с парком. Три спальни, просторная кухня и гостиная.', amenities: ['Wi‑Fi', 'Кондиционер', 'Кухня', 'Стиральная машина', 'Телевизор', 'Балкон', 'Детская мебель'] },
  { id: 7, city: 'moscow', cityName: 'Москва', type: 'daily', title: 'Студия у Парка Горького', meta: 'Крымская · до 2 гостей', price: 'от 4 100 ₽', priceUnit: '/ ночь', priceNight: 4100, priceMonth: 0, image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=400&fit=crop', description: 'Уютная студия в двух шагах от Парка Горького. Идеально для отдыха и прогулок.', amenities: ['Wi‑Fi', 'Кондиционер', 'Кухня', 'Стиральная машина'] },
  { id: 8, city: 'moscow', cityName: 'Москва', type: 'long', title: 'Двушка с ремонтом у метро', meta: 'Юго-Западная · до 4 гостей', price: 'от 78 000 ₽', priceUnit: '/ месяц', priceNight: 0, priceMonth: 78000, image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&h=400&fit=crop', description: 'Свежий ремонт, вся техника. Тихий двор, рядом метро и магазины.', amenities: ['Wi‑Fi', 'Кондиционер', 'Кухня', 'Стиральная машина', 'Балкон'] },
  { id: 9, city: 'piter', cityName: 'Питер', type: 'daily', title: 'Студия на Невском', meta: 'Невский проспект · до 2 гостей', price: 'от 3 800 ₽', priceUnit: '/ ночь', priceNight: 3800, priceMonth: 0, image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=400&fit=crop', description: 'Студия в самом центре Петербурга. Вид на Невский, все достопримечательности рядом.', amenities: ['Wi‑Fi', 'Кондиционер', 'Кухня', 'Стиральная машина', 'Телевизор'] },
  { id: 10, city: 'piter', cityName: 'Питер', type: 'long', title: 'Двухкомнатная на Васильевском', meta: 'Васильевский остров · до 4 гостей', price: 'от 72 000 ₽', priceUnit: '/ месяц', priceNight: 0, priceMonth: 72000, image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&h=400&fit=crop', description: 'Просторная двушка с видом на залив. Транспорт и метро рядом.', amenities: ['Wi‑Fi', 'Кондиционер', 'Кухня', 'Стиральная машина', 'Балкон'] },
  { id: 11, city: 'piter', cityName: 'Питер', type: 'daily', title: 'Апартаменты у Эрмитажа', meta: 'Дворцовая наб. · до 3 гостей', price: 'от 6 500 ₽', priceUnit: '/ ночь', priceNight: 6500, priceMonth: 0, image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&h=400&fit=crop', description: 'Роскошные апартаменты с видом на Дворцовую набережную. Историческое здание.', amenities: ['Wi‑Fi', 'Кондиционер', 'Кухня', 'Стиральная машина', 'Телевизор', 'Посудомойка'] },
  { id: 12, city: 'piter', cityName: 'Питер', type: 'long', title: 'Однушка на Петроградской', meta: 'Петроградская · до 2 гостей', price: 'от 58 000 ₽', priceUnit: '/ месяц', priceNight: 0, priceMonth: 58000, image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600&h=400&fit=crop', description: 'Уютная однушка в тихом районе. Метро 5 минут, парк и кафе рядом.', amenities: ['Wi‑Fi', 'Кондиционер', 'Кухня', 'Стиральная машина'] },
  { id: 13, city: 'piter', cityName: 'Питер', type: 'daily', title: 'Лофт на Лиговском', meta: 'Лиговский · до 4 гостей', price: 'от 5 900 ₽', priceUnit: '/ ночь', priceNight: 5900, priceMonth: 0, image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=600&h=400&fit=crop', description: 'Стильный лофт в бывшем заводе. Высокие потолки, открытое пространство.', amenities: ['Wi‑Fi', 'Кондиционер', 'Кухня', 'Стиральная машина', 'Парковка'] },
  { id: 14, city: 'piter', cityName: 'Питер', type: 'long', title: 'Трёхкомнатная у метро Московская', meta: 'Московский р-н · до 5 гостей', price: 'от 95 000 ₽', priceUnit: '/ месяц', priceNight: 0, priceMonth: 95000, image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=600&h=400&fit=crop', description: 'Большая квартира для семьи. Тихий район, хорошая транспортная доступность.', amenities: ['Wi‑Fi', 'Кондиционер', 'Кухня', 'Стиральная машина', 'Балкон', 'Детская мебель'] },
  { id: 15, city: 'piter', cityName: 'Питер', type: 'daily', title: 'Студия у Казанского собора', meta: 'Казанская · до 2 гостей', price: 'от 4 200 ₽', priceUnit: '/ ночь', priceNight: 4200, priceMonth: 0, image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=400&fit=crop', description: 'Идеальное расположение для туристов. Невский, Дворцовая, Эрмитаж — всё рядом.', amenities: ['Wi‑Fi', 'Кондиционер', 'Кухня'] },
  { id: 16, city: 'sochi', cityName: 'Сочи', type: 'daily', title: 'Студия у моря в Имеретинке', meta: 'Имеретинский · до 2 гостей', price: 'от 4 500 ₽', priceUnit: '/ ночь', priceNight: 4500, priceMonth: 0, image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=400&fit=crop', description: 'Студия в 5 минутах от пляжа. Бассейн, парковка, вид на море.', amenities: ['Wi‑Fi', 'Кондиционер', 'Кухня', 'Бассейн', 'Парковка'] },
  { id: 17, city: 'sochi', cityName: 'Сочи', type: 'long', title: 'Двушка в центре Сочи', meta: 'Центральный район · до 4 гостей', price: 'от 75 000 ₽', priceUnit: '/ месяц', priceNight: 0, priceMonth: 75000, image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&h=400&fit=crop', description: 'Квартира в центре города. Море и набережная рядом, вся инфраструктура.', amenities: ['Wi‑Fi', 'Кондиционер', 'Кухня', 'Стиральная машина', 'Балкон'] },
  { id: 18, city: 'sochi', cityName: 'Сочи', type: 'daily', title: 'Апартаменты с видом на море', meta: 'Лазаревское · до 3 гостей', price: 'от 6 200 ₽', priceUnit: '/ ночь', priceNight: 6200, priceMonth: 0, image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&h=400&fit=crop', description: 'Панорамный вид на море. Собственный пляж, ресторан в доме.', amenities: ['Wi‑Fi', 'Кондиционер', 'Кухня', 'Стиральная машина', 'Вид на море'] },
  { id: 19, city: 'sochi', cityName: 'Сочи', type: 'long', title: 'Однушка в Адлере', meta: 'Адлер · до 2 гостей', price: 'от 52 000 ₽', priceUnit: '/ месяц', priceNight: 0, priceMonth: 52000, image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600&h=400&fit=crop', description: 'Удобная квартира рядом с Олимпийским парком и морем.', amenities: ['Wi‑Fi', 'Кондиционер', 'Кухня', 'Стиральная машина'] },
  { id: 20, city: 'sochi', cityName: 'Сочи', type: 'daily', title: 'Вилла у моря Красная Поляна', meta: 'Красная Поляна · до 6 гостей', price: 'от 12 000 ₽', priceUnit: '/ ночь', priceNight: 12000, priceMonth: 0, image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=600&h=400&fit=crop', description: 'Просторный дом для большой компании. Горы, природа, комфорт.', amenities: ['Wi‑Fi', 'Кондиционер', 'Кухня', 'Стиральная машина', 'Парковка', 'Терраса'] },
  { id: 21, city: 'sochi', cityName: 'Сочи', type: 'long', title: 'Трёхкомнатная у моря', meta: 'Курортный городок · до 6 гостей', price: 'от 110 000 ₽', priceUnit: '/ месяц', priceNight: 0, priceMonth: 110000, image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=600&h=400&fit=crop', description: 'Большая квартира в курортном комплексе. Пляж, бассейн, детская площадка.', amenities: ['Wi‑Fi', 'Кондиционер', 'Кухня', 'Стиральная машина', 'Балкон', 'Бассейн'] },
  { id: 22, city: 'mytishi', cityName: 'Мытищи', type: 'daily', title: 'Студия у ж/д вокзала', meta: 'Центр · до 2 гостей', price: 'от 2 800 ₽', priceUnit: '/ ночь', priceNight: 2800, priceMonth: 0, image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=400&fit=crop', description: 'Удобная студия для поездок в Москву. 20 минут до Ярославского вокзала.', amenities: ['Wi‑Fi', 'Кондиционер', 'Кухня', 'Стиральная машина'] },
  { id: 23, city: 'mytishi', cityName: 'Мытищи', type: 'long', title: 'Двухкомнатная в новостройке', meta: 'Новый район · до 4 гостей', price: 'от 45 000 ₽', priceUnit: '/ месяц', priceNight: 0, priceMonth: 45000, image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&h=400&fit=crop', description: 'Новая квартира с ремонтом. Тихий двор, парковка, магазины рядом.', amenities: ['Wi‑Fi', 'Кондиционер', 'Кухня', 'Стиральная машина', 'Балкон'] },
  { id: 24, city: 'mytishi', cityName: 'Мытищи', type: 'daily', title: 'Однушка для командировочных', meta: 'ул. Мира · до 2 гостей', price: 'от 2 500 ₽', priceUnit: '/ ночь', priceNight: 2500, priceMonth: 0, image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600&h=400&fit=crop', description: 'Чистая, уютная квартира. Остановка и ж/д в шаговой доступности.', amenities: ['Wi‑Fi', 'Кондиционер', 'Кухня'] },
  { id: 25, city: 'mytishi', cityName: 'Мытищи', type: 'long', title: 'Трёхкомнатная для семьи', meta: 'Перловка · до 5 гостей', price: 'от 55 000 ₽', priceUnit: '/ месяц', priceNight: 0, priceMonth: 55000, image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=600&h=400&fit=crop', description: 'Просторная квартира в зелёном районе. Школы, садики, поликлиника рядом.', amenities: ['Wi‑Fi', 'Кондиционер', 'Кухня', 'Стиральная машина', 'Балкон'] },
  { id: 26, city: 'mytishi', cityName: 'Мытищи', type: 'daily', title: 'Студия с кухней-нишей', meta: 'ЖК Мытищи Парк · до 2 гостей', price: 'от 3 100 ₽', priceUnit: '/ ночь', priceNight: 3100, priceMonth: 0, image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=400&fit=crop', description: 'Современная студия в новом жилом комплексе. Отличная транспортная доступность.', amenities: ['Wi‑Fi', 'Кондиционер', 'Кухня', 'Стиральная машина'] },
  { id: 27, city: 'korolev', cityName: 'Королёв', type: 'daily', title: 'Студия у вокзала Королёв', meta: 'Центр · до 2 гостей', price: 'от 2 900 ₽', priceUnit: '/ ночь', priceNight: 2900, priceMonth: 0, image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=400&fit=crop', description: 'Удобно для поездок в Москву и в наукоград. Чисто, всё необходимое.', amenities: ['Wi‑Fi', 'Кондиционер', 'Кухня', 'Стиральная машина'] },
  { id: 28, city: 'korolev', cityName: 'Королёв', type: 'long', title: 'Двухкомнатная в Королёве', meta: 'ул. Калининская · до 4 гостей', price: 'от 48 000 ₽', priceUnit: '/ месяц', priceNight: 0, priceMonth: 48000, image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&h=400&fit=crop', description: 'Уютная двушка для длительного проживания. Метро Щёлковская — 15 мин на автобусе.', amenities: ['Wi‑Fi', 'Кондиционер', 'Кухня', 'Стиральная машина', 'Балкон'] },
  { id: 29, city: 'korolev', cityName: 'Королёв', type: 'daily', title: 'Однушка для гостей РКК', meta: 'Подлипки · до 2 гостей', price: 'от 3 200 ₽', priceUnit: '/ ночь', priceNight: 3200, priceMonth: 0, image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600&h=400&fit=crop', description: 'Идеально для командировок в предприятия города. Тихий район.', amenities: ['Wi‑Fi', 'Кондиционер', 'Кухня'] },
  { id: 30, city: 'korolev', cityName: 'Королёв', type: 'long', title: 'Однокомнатная в новостройке', meta: 'ЖК Болшево · до 2 гостей', price: 'от 42 000 ₽', priceUnit: '/ месяц', priceNight: 0, priceMonth: 42000, image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600&h=400&fit=crop', description: 'Новая квартира с отделкой. Парк и инфраструктура рядом.', amenities: ['Wi‑Fi', 'Кондиционер', 'Кухня', 'Стиральная машина'] },
  { id: 31, city: 'korolev', cityName: 'Королёв', type: 'daily', title: 'Двушка посуточно', meta: 'ул. Циолковского · до 4 гостей', price: 'от 4 500 ₽', priceUnit: '/ ночь', priceNight: 4500, priceMonth: 0, image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&h=400&fit=crop', description: 'Просторная квартира для семьи или компании. Удобный выезд на МКАД и Ярославку.', amenities: ['Wi‑Fi', 'Кондиционер', 'Кухня', 'Стиральная машина', 'Парковка'] }
];

/* City display names for filters */
window.CITIES = [
  { key: 'all', name: 'Все города' },
  { key: 'moscow', name: 'Москва' },
  { key: 'piter', name: 'Питер' },
  { key: 'sochi', name: 'Сочи' },
  { key: 'mytishi', name: 'Мытищи' },
  { key: 'korolev', name: 'Королёв' }
];
